Documentation:
    Enabled: false

Metrics/LineLength:
  Max: 100
  Exclude:
    - spec/**/*.rb

# Metrics/MethodLength:
#   Max: 20

# Metrics/ClassLength:
#   Max: 200

Metrics/BlockLength:
  #   Max: 50
  # Ignore Metrics/BlockLength for the spec directory
  Exclude:
    - spec/**/*.rb
